# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd4a1960114e8b76dfe0f03c32adc148f40d2fb6229e74023d410ba06b2428073cf4677a551b1dd9cdd66a46d650f530fbb92992657fcb80096b636dd0fcff81

test:
  secret_key_base: 7196f9162486badec99773c3bbeb4b03dc51f7c447d40da236e0011dd5a31780d86ef6f200453f8ddf9a0907fac0682dcd302c92369897f93830501fd926e3d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
